server:
  port: 16969

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: wuhb9208
    driver-class-name: com.mysql.cj.jdbc.Driver
